[features]
seeds = false
skip-lint = false

[programs.localnet]
config = "DWiwuFozPXHW4KA5ijwcDgY88kJeXZ7WNUjfxZ6L4pJU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
