[features]
seeds = false
skip-lint = false

[programs.localnet]
config = "3D4TTrhnPhV3ULrjEZ9xeaQHUN776KMzMGGB2Pp5H8bB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "YOUR_WALLET_PATH_HERE"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
