[features]
seeds = false
skip-lint = false

[programs.localnet]
config = "G839pmstFmKKGEVXRGnauXxFgzucvELrzuyk6gHTiK7a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
